name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: init module
        run: go mod init staci

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

 #     - name: Build 
 #       run: go build -v .
        
 #     - name: Test
 #       run: go test -v .

      - name: go-crossbuild
        uses: izumin5210/action-go-crossbuild@v1.0.0
        with:
          # An application name
          name: staci
          # Space or comma separated list of GOARCH
          arch: amd64, arm64
          # Path to destination directory of built binaries
          # dest: # optional, default is ./dist
          # `-ldflags` to pass to go build
          # ldflags: # optional, default is 
          # `-tags` to pass to go build
          # tags: # optional, default is 
          # Space or comma separated list of GOOS
          os: darwin,linux,windows
          # Build target package
          # package: # optional, default is .
          # Version of github.com/Songmu/goxz
          # goxz-version: # optional, default is v0.4.1
          
      - name: Archive latest artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-all
          path: |
            dist

      - name: Upload to Release Action
        # You may pin to the exact commit or the version.
        # uses: Shopify/upload-to-release@9942a4c936dab172f7101dcc7dc20528ea949102
        uses: Shopify/upload-to-release@v1.0.1
        with:
          # Artifact name
          name: dist-all
          # Path to the file to upload
          path: dist/*

          
          

