name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: init module
        run: go mod init staci

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build 
        run: go build -v .
        
      - name: Test
        run: go test -v .

      - name: go-crossbuild
        uses: izumin5210/action-go-crossbuild@v1.0.0
        with:
          # An application name
          name: staci
          # Space or comma separated list of GOARCH
          arch: amd64, arm64
          # Path to destination directory of built binaries
          # dest: # optional, default is ./dist
          # `-ldflags` to pass to go build
          # ldflags: # optional, default is 
          # `-tags` to pass to go build
          # tags: # optional, default is 
          # Space or comma separated list of GOOS
          os: darwin,linux,windows
          # Build target package
          # package: # optional, default is .
          # Version of github.com/Songmu/goxz
          # goxz-version: # optional, default is v0.4.1
          
      - name: Release & Assets
        # You may pin to the exact commit or the version.
        # uses: Hs1r1us/Release-AIO@c2a7f552ef323d9411be1862e47ddd2e3eaf8893
        uses: Hs1r1us/Release-AIO@v2.0.0
        with:
          # The name of the tag
          tag_name: latest
          # The name of the release
          release_name: latest
          # The path to the asset you want to upload
          asset_files: dist/*
          # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
          prerelease: true

          
          

